name: pytorch_lipophilicity
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
  - pyg=*=*cu116
  - tqdm
  - mkl==2024.0
  - pip=22.3.1
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - rdkit
    - dgllife
    - networkx